*-------Realizando la conexion
SET PATH TO Formulario,Menus,Programa,Clases,Reporte,Imagenes,Include,Com

SET DATE TO dmy
SET MARK TO "/"
SET NULL OFF
SET NULLDISPLAY TO ''

SET SAFETY OFF
SET CENTURY on
SET MULTILOCKS ON
SET TALK OFF
SET DELETED ON
SET DECIMALS TO 0
SET NOTIF OFF
SET NULL OFF
SET NULLDISPLAY TO ''
SET REPORTBEHAVIOR 80
SET NOTIFY OFF
SET PROCEDURE TO funciones.prg
PUBLIC CN 
CN = RECONECCION() 
IF CN > 0
	MESSAGEBOX("LA CONEXION SE REALIZO CON EXITO, PUEDE EJECUTAR EL EJEMPLO DEL GRIDLIBRE",64,"Infromacion...")
ELSE
	MESSAGEBOX("NO SE PUEDO REALIZAR LA CONEXION, VEREFIQUE",16,"Advertencia...")
ENDIF 